AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Resources:
  MyFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: test2.handler
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      CodeUri: .
      Timeout: 30 # Timeout duration in seconds
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /hello
            Method: get
